# Generated by Django 4.1.7 on 2023-03-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
